service: combine-icons-with-text

image: mousu-a/combine_icons_with_text

servers:
  web:
    - 153.126.135.118

proxy:
  ssl: true
  host: icon-font-mashup.com

registry:
  server: ghcr.io
  username: mousu-a

password:
  - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "combine_icons_with_text_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: tao
  port: 2222

accessories:
  db:
    image: postgres:17-bookworm
    roles:
      - web
    env:
      clear:
        POSTGRES_DB: combine_icons_with_text_production
        POSTGRES_USER: combine_icons_with_text
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pg-data:/var/lib/postgresql/data
